fs 		= require 'fs'
{exec} 	= require 'child_process'

config 	= require './../src/config.json'

task "build", "build the plugin", ->
	exec "start build.bat"

task "config", "Update config in plugin.moon", ->
	code = fs.readFileSync "plugin.moon", encoding: "utf8"
	code = code.replace /BUILD=[0-9]+/, "BUILD=#{config.BUILD}"
	code = code.replace /PORT=[0-9]+/, "PORT=#{config.PORT}"
	fs.writeFileSync "plugin.moon", code